name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Build the Docker image
        run: |
          docker build backend \
            --file backend/Dockerfile \
            --tag my-image-name:${{ github.sha }}

      # (optional) push to Docker Hub or GitHub Container Registry:
      #- name: Log in to registry
      #  run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
      #- name: Push image
      #  run: docker push my-image-name:${{ github.sha }}
