jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14           # pick the version you want
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U testuser -d testdb"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm

      # root install (if needed)
      - name: Install root deps
        run: npm ci

      # backend install & test
      - name: Install backend deps
        run: npm install
        working-directory: progettoWeb/backend

      - name: Run backend tests
        run: npm test
        working-directory: progettoWeb/backend
        env:
          # point your tests at the service
          PGHOST: localhost
          PGPORT: 5432
          PGUSER: testuser
          PGPASSWORD: testpass
          PGDATABASE: testdb
